<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SunilNad_Lenevo330" ignored="0" name="EdgeTest" tests="5" failures="1" timestamp="2021-07-01T20:06:33 IST" time="15.828" errors="0">
  <testcase name="method4" time="0.927" classname="tests.Test1"/>
  <testcase name="method1" time="1.069" classname="tests.Test1">
    <failure type="java.lang.AssertionError" message="failing... ">
      <![CDATA[java.lang.AssertionError: failing... 
at tests.Test1.method1(Test1.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method5" time="1.33" classname="tests.Test1"/>
  <testcase name="method3" time="1.246" classname="tests.Test1"/>
  <testcase name="method2" time="0.284" classname="tests.Test1"/>
</testsuite> <!-- EdgeTest -->
